#!/bin/bash
# User variables.
SRC_PATH=example-java/src/main/java/
USE_JMLCUTE=$1
CUTE_ARGS="-p:1"

# Prepare.
TARGET_DIR=target/
CLASSES_DIR=classes/
GENERATED_SOURCES_DIR=generated-sources/
GENERATED_TEST_SOURCES_DIR=generated-test-sources/
mkdir -p $TARGET_DIR
cd $TARGET_DIR
mkdir -p $CLASSES_DIR
mkdir -p $GENERATED_SOURCES_DIR
mkdir -p $GENERATED_TEST_SOURCES_DIR

TARGET_DIR=.
SRC_PATH=../$SRC_PATH
JMLCUTE_PROCESSED_CLASSES_JAR=jmlcute-processed-classes.jar
JMLCUTE_JARS=$CLASSES_DIR:../jars/jmlmodelsnonrac.jar
SOOT_JAR=../jars/sootclasses-2.2.3.jar
export PATH=$PATH:..
export JAVA_LIB_PATH=../jars
export LD_LIBRARY_PATH=../jars

JAVA_FILES="$(find $SRC_PATH/eventb_prelude $SRC_PATH/Util $SRC_PATH/binary_search_sequential -name "*.java" | tr "\n" " ")"

if [[ $USE_JMLCUTE == "-no-jml" ]]
then
  shift
  # Compile.
  export CLASSPATH=$JMLCUTE_JARS
  javac -d $CLASSES_DIR -sourcepath $SRC_PATH $JAVA_FILES
else
  # Print Aspects.
  export CLASSPATH=$JMLCUTE_JARS:$SRC_PATH
  java org.jmlspecs.ajmlrac.Main --destination $CLASSES_DIR --classpath $CLASSPATH --source=1.7 \
  --crosscuttingContractSpecifications --adviceChecking --defaultNonNull --noredundancy \
  --crosscuttingContractSpecifications --Quiet --purity $JAVA_FILES
fi

# Generate Test Cases
# SOOT_JAR must come before JMLCUTE_JARS in the classpath.
export CLASSPATH=$CLASSES_DIR:$SOOT_JAR:$JMLCUTE_JARS
java -Xmx900m -Djava.library.path="$JAVA_LIB_PATH" -Dcute.sequential=true -Dcute.args="$CUTE_ARGS" pt.ulisboa.tecnico.TestCaseGeneratorApp \
  -main-generate-d $GENERATED_SOURCES_DIR \
  -main-compile-d $CLASSES_DIR \
  -main-instrument-jar $JMLCUTE_PROCESSED_CLASSES_JAR \
  -test-cases-d $GENERATED_TEST_SOURCES_DIR \
  $@
