/**
 * Generated by AspectJML.
 */
public privileged aspect AspectJMLRac_pt_ulisboa_tecnico_Add {
 declare precedence: AspectJMLRac_*, *;

  /**
   * Precondition of method execute.
   */
  before (final pt.ulisboa.tecnico.Add object$rac, final int x, final int y) :
    (execution(int pt.ulisboa.tecnico.Add.execute(int, int))) &&
    this(object$rac) && args(x, y) {
      cute.Cute.Assert(((x > 0) && (y > 0)));
    }
}

